/**
 * Caelestis — DM Space Navigation
 * ────────────────────────────────
 * Injects the DM-space sidebar nav with expandable, cross-page section
 * navigation. Parallel to scripts/nav.js but for /prime/.
 *
 * Each pillar can expand to reveal that page's first-level (h2) sections,
 * read from the window.DM_SECTIONS manifest (scripts/dm-sections.js, which
 * is auto-generated by scripts/generate-sections.js). Clicking a section:
 *   - on the current page  → smooth-scrolls to it (with scroll-spy highlight)
 *   - on another page       → navigates to page.html#section
 *
 * Load order in <head> (defer): dm-sections.js BEFORE dm-nav.js.
 *   /prime/*.html:           <script src="../scripts/dm-sections.js" defer></script>
 *                            <script src="../scripts/dm-nav.js" defer></script>
 *   /prime/voyages/*.html:   <script src="../../scripts/dm-sections.js" defer></script>
 *                            <script src="../../scripts/dm-nav.js" defer></script>
 */

(function () {
  'use strict';

  // ── Path resolution ───────────────────────────────────────────────────────
  var pathname = window.location.pathname;
  var primeIdx = pathname.indexOf('/prime/');
  var afterPrime = primeIdx >= 0 ? pathname.slice(primeIdx + 7) : '';
  var primeDepth = (afterPrime.match(/\//g) || []).length;
  var base = primeDepth > 0 ? new Array(primeDepth + 1).join('../') : './';
  var siteBase = base + '../';

  // The current page key, relative to /prime/ — e.g. 'continuum.html' or
  // 'voyages/index.html'. Used to match the manifest and detect same-page links.
  var currentKey = afterPrime || 'index.html';
  // Normalize a bare /prime/ or /prime/voyages/ (directory) to its index.
  if (currentKey === '' ) currentKey = 'index.html';
  if (/\/$/.test(currentKey)) currentKey += 'index.html';

  // ── Icons ─────────────────────────────────────────────────────────────────
  var EXT_ICON = '<svg viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 2H2a1 1 0 00-1 1v5a1 1 0 001 1h5a1 1 0 001-1V6M6 1h3v3M9 1L4.5 5.5"/></svg>';
  var MENU_ICON = '<svg viewBox="0 0 18 14" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><line x1="0" y1="1" x2="18" y2="1"/><line x1="0" y1="7" x2="18" y2="7"/><line x1="0" y1="13" x2="18" y2="13"/></svg>';
  var CARET = '<svg class="side-nav-caret" viewBox="0 0 8 8" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2.5 1.5L5.5 4l-3 2.5"/></svg>';

  // ── Pillars ───────────────────────────────────────────────────────────────
  // Internal pages inside /prime/. `key` matches the manifest + the filename.
  // `group` controls placement around the throughline divider:
  //   'reference' = top block (cosmology / design / world)
  //   'throughline' = bottom block (the trackable spines)
  // `indent` nests a pillar visually under the previous one.

  var pillars = [
    { key: 'continuum.html', label: 'Continuum',    group: 'reference'   },
    { key: 'campaign.html',  label: 'Campaign',     group: 'reference'   },
    { key: 'seeds.html',     label: 'Seeds',        group: 'reference', indent: true },
    { key: 'world.html',     label: 'World',        group: 'reference'   },
    { key: 'factions.html',  label: 'Factions',     group: 'reference', indent: true },
    { key: 'remaking.html',  label: 'The Remaking', group: 'throughline' },
    { key: 'voyages/index.html', label: 'Voyages',  group: 'throughline' },
  ];

  var extLinks = [
    { label: 'Campaign Tracker',     href: 'https://docs.google.com/spreadsheets/d/1m4V9t2Z6hq0rjeUVZyTooNI8LMGOrd9gHezWY9o5-nY/edit' },
    { label: 'Character Tracker',    href: 'https://docs.google.com/spreadsheets/d/1UbXgV-SDR_gMit1qTJl9tqrBxZVr__Ef7W1MHQ1dYew/edit' },
    { label: 'Wildspace Tracker',    href: 'https://docs.google.com/spreadsheets/d/1Bwu1iG0Xd3SgFzoiP8Kuqo7DVGBR0H-qPo_G77dOg8E/edit' },
    { label: 'Wildspace Lore Bible', href: 'https://docs.google.com/document/d/1XjOAGPAWvDivwI2ThihwCG84ACk2eF_HKtzbxgbVTMQ/edit' },
    { label: 'Crew Logs',            href: 'https://docs.google.com/document/d/1BHK5I0sLMoEUCDQ89Qic1tqkup7KPMQbZ01Ko6vnnLU/edit' },
    { label: 'Drive Root',           href: 'https://drive.google.com/drive/folders/1suJFIN_LYDmRrkzjk3PkVv2pOmbJxE8r' },
    { label: 'Player Site',          href: siteBase + 'index.html' },
  ];

  // ── Critical positioning CSS (prevents flash) ─────────────────────────────
  var criticalCSS = [
    '.side-nav{position:fixed!important;left:0;top:0;bottom:0;width:220px;z-index:200;',
    'display:flex;flex-direction:column;overflow-y:auto;',
    'background:rgba(6,4,14,0.99);border-right:1px solid rgba(201,153,58,0.15);}',
    '.side-nav-toggle{display:none!important;position:fixed!important;z-index:201;}',
    'body.with-sidebar{padding-left:220px;}',
    '@media(max-width:768px){',
    'body.with-sidebar{padding-left:0!important;padding-top:52px!important;}',
    '.side-nav{transform:translateX(-100%);transition:transform .28s ease;}',
    '.side-nav.open{transform:translateX(0);}',
    '.side-nav-toggle{display:flex!important;top:0;left:0;right:0;height:44px;}',
    '}'
  ].join('');
  var styleEl = document.createElement('style');
  styleEl.textContent = criticalCSS;
  document.head.appendChild(styleEl);

  // ── Section manifest ──────────────────────────────────────────────────────
  var SECTIONS = window.DM_SECTIONS || {};

  function sectionsFor(key) {
    return SECTIONS[key] || [];
  }

  // ── Build a single pillar (link + optional expandable section list) ───────
  function buildPillar(p) {
    var isCurrent = (p.key === currentKey);
    var secs = sectionsFor(p.key);
    var hasSecs = secs.length > 0;

    var classes = ['side-nav-pillar'];
    if (p.indent) classes.push('is-indent');
    if (isCurrent) classes.push('is-current');
    if (hasSecs) classes.push('has-sections');
    // The active pillar starts expanded; others start collapsed.
    if (isCurrent && hasSecs) classes.push('is-expanded');

    var rowParts = [];
    // Caret toggles expansion (only if there are sections).
    if (hasSecs) {
      rowParts.push('<button class="side-nav-caret-btn" aria-label="Toggle sections" data-pillar="' + p.key + '">' + CARET + '</button>');
    } else {
      rowParts.push('<span class="side-nav-caret-spacer"></span>');
    }
    rowParts.push('<a class="side-nav-link" href="' + base + p.key + '" data-pillar-key="' + p.key + '">' + p.label + '</a>');

    var sublist = '';
    if (hasSecs) {
      var items = secs.map(function (s) {
        var href = base + p.key + '#' + s.id;
        return '<a class="side-nav-sub" href="' + href + '" data-section-id="' + s.id + '" data-page="' + p.key + '">' + s.label + '</a>';
      }).join('');
      sublist = '<div class="side-nav-sublist">' + items + '</div>';
    }

    return '<div class="' + classes.join(' ') + '" data-pillar="' + p.key + '">' +
           '<div class="side-nav-row">' + rowParts.join('') + '</div>' +
           sublist +
           '</div>';
  }

  var referencePillars = pillars.filter(function (p) { return p.group === 'reference'; }).map(buildPillar).join('');
  var throughlinePillars = pillars.filter(function (p) { return p.group === 'throughline'; }).map(buildPillar).join('');

  var externalLinks = extLinks.map(function (l) {
    return '<a class="side-nav-ext-link" href="' + l.href + '" target="_blank" rel="noopener">' + l.label + ' ' + EXT_ICON + '</a>';
  }).join('');

  var signOutLink = '<a class="side-nav-ext-link side-nav-signout" href="#" id="js-dm-signout">Sign out</a>';

  var html = [
    '<button class="side-nav-toggle" id="js-nav-toggle" aria-label="Toggle navigation">',
    MENU_ICON,
    '<span class="side-nav-toggle-label">Caelestis · DM</span>',
    '</button>',
    '<nav class="side-nav" id="js-side-nav">',
    '  <div class="side-nav-head">',
    '    <a class="side-nav-logo" href="' + base + 'hub.html">Caelestis · DM</a>',
    '  </div>',
    '  <div class="side-nav-body">',
    referencePillars,
    '    <div class="side-nav-divider"></div>',
    throughlinePillars,
    '    <div class="side-nav-divider"></div>',
    externalLinks,
    '    <div class="side-nav-divider"></div>',
    signOutLink,
    '  </div>',
    '</nav>',
  ].join('');

  // ── Inject ────────────────────────────────────────────────────────────────
  document.body.insertAdjacentHTML('afterbegin', html);
  document.body.classList.add('with-sidebar');

  var nav = document.getElementById('js-side-nav');

  // ── Active pillar highlight ───────────────────────────────────────────────
  var currentPillarEl = nav.querySelector('.side-nav-pillar.is-current');
  if (currentPillarEl) {
    var currentLink = currentPillarEl.querySelector('.side-nav-link');
    if (currentLink) currentLink.classList.add('active');
  }

  // ── Caret expand/collapse ─────────────────────────────────────────────────
  nav.querySelectorAll('.side-nav-caret-btn').forEach(function (btn) {
    btn.addEventListener('click', function (e) {
      e.preventDefault();
      e.stopPropagation();
      var pillar = btn.closest('.side-nav-pillar');
      if (pillar) pillar.classList.toggle('is-expanded');
    });
  });

  // ── Same-page section links: smooth-scroll instead of navigating ──────────
  nav.querySelectorAll('.side-nav-sub').forEach(function (link) {
    var page = link.dataset.page;
    if (page === currentKey) {
      link.addEventListener('click', function (e) {
        var id = link.dataset.sectionId;
        var target = document.getElementById(id);
        if (target) {
          e.preventDefault();
          target.scrollIntoView({ behavior: 'smooth', block: 'start' });
          history.replaceState(null, '', '#' + id);
          if (nav.classList.contains('open')) nav.classList.remove('open');
        }
      });
    }
    // Cross-page links use their plain href (page.html#id) — default behavior.
  });

  // ── Scroll-spy for the current page's sections ────────────────────────────
  (function scrollSpy() {
    if (!currentPillarEl) return;
    var subLinks = {};
    currentPillarEl.querySelectorAll('.side-nav-sub').forEach(function (link) {
      subLinks[link.dataset.sectionId] = link;
    });
    var ids = Object.keys(subLinks);
    if (!ids.length) return;

    var headings = ids
      .map(function (id) { return document.getElementById(id); })
      .filter(Boolean);
    if (!headings.length) return;

    var visible = {};
    var lastActive = null;

    function setActive(id) {
      if (id === lastActive) return;
      if (lastActive && subLinks[lastActive]) subLinks[lastActive].classList.remove('is-active-sub');
      if (id && subLinks[id]) subLinks[id].classList.add('is-active-sub');
      lastActive = id;
    }

    function recompute() {
      var best = null, bestTop = Infinity;
      headings.forEach(function (h) {
        if (visible[h.id]) {
          var top = h.getBoundingClientRect().top;
          if (top < bestTop) { bestTop = top; best = h.id; }
        }
      });
      if (best) { setActive(best); return; }
      var above = null;
      headings.forEach(function (h) {
        if (h.getBoundingClientRect().top < 120) above = h.id;
      });
      if (above) setActive(above);
    }

    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) { visible[entry.target.id] = entry.isIntersecting; });
      recompute();
    }, { rootMargin: '-10% 0px -75% 0px', threshold: 0 });

    headings.forEach(function (h) { observer.observe(h); });
    recompute();
  })();

  // ── Mobile toggle ─────────────────────────────────────────────────────────
  var toggle = document.getElementById('js-nav-toggle');
  if (toggle && nav) {
    toggle.addEventListener('click', function (e) {
      e.stopPropagation();
      nav.classList.toggle('open');
    });
    document.addEventListener('click', function (e) {
      if (nav.classList.contains('open') && !nav.contains(e.target)) {
        nav.classList.remove('open');
      }
    });
    nav.querySelectorAll('.side-nav-link').forEach(function (link) {
      link.addEventListener('click', function () { nav.classList.remove('open'); });
    });
  }

  // ── Sign Out ──────────────────────────────────────────────────────────────
  var signOut = document.getElementById('js-dm-signout');
  if (signOut) {
    signOut.addEventListener('click', function (e) {
      e.preventDefault();
      try { sessionStorage.removeItem('caelestis_continuum_auth'); } catch (err) { /* ignore */ }
      window.location.replace(base + 'index.html');
    });
  }

})();
